namespace ErsatzTV.Core.Security;

public static class PublicBlocklistCatalog
{
    private static readonly TimeSpan Daily = TimeSpan.FromHours(24);
    private static readonly TimeSpan Hourly = TimeSpan.FromHours(1);
    private static readonly TimeSpan EveryTwoHours = TimeSpan.FromHours(2);

    public static IReadOnlyList<PublicBlocklistDefinition> All { get; } =
    [
        Define(
            "ipsum-1",
            "IPsum Level 1",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/1.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: false,
            defaultEnabled: false,
            Daily,
            "IPs appearing on 1+ public blacklists. Very broad; higher false-positive risk.",
            "IPsum"),
        Define(
            "ipsum-2",
            "IPsum Level 2",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/2.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: false,
            defaultEnabled: false,
            Daily,
            "IPs appearing on 2+ public blacklists.",
            "IPsum"),
        Define(
            "ipsum-3",
            "IPsum Level 3",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: true,
            Daily,
            "IPs appearing on 3+ public blacklists. Good balance for admin protection.",
            "IPsum"),
        Define(
            "ipsum-4",
            "IPsum Level 4",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/4.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: true,
            Daily,
            "IPs appearing on 4+ public blacklists.",
            "IPsum"),
        Define(
            "ipsum-5",
            "IPsum Level 5",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/5.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: true,
            Daily,
            "IPs appearing on 5+ public blacklists. Stricter with fewer false positives.",
            "IPsum"),
        Define(
            "ipsum-6",
            "IPsum Level 6",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/6.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: false,
            Daily,
            "IPs appearing on 6+ public blacklists. High confidence.",
            "IPsum"),
        Define(
            "ipsum-7",
            "IPsum Level 7",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/7.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: false,
            Daily,
            "IPs appearing on 7+ public blacklists. Very high confidence.",
            "IPsum"),
        Define(
            "ipsum-8",
            "IPsum Level 8",
            "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/8.txt",
            "stamparm/ipsum",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: false,
            Daily,
            "IPs appearing on 8+ public blacklists. Smallest, strictest IPsum tier.",
            "IPsum"),
        Define(
            "firehol-l1",
            "FireHOL Level 1",
            "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset",
            "firehol/blocklist-ipsets",
            PublicBlocklistFormat.Mixed,
            recommended: false,
            defaultEnabled: false,
            Daily,
            "Large CIDR ranges including bogons and DROP lists. Can block legitimate traffic; use with caution.",
            "FireHOL"),
        Define(
            "firehol-l2",
            "FireHOL Level 2",
            "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset",
            "firehol/blocklist-ipsets",
            PublicBlocklistFormat.Mixed,
            recommended: true,
            defaultEnabled: true,
            Daily,
            "Recent attack sources from the last ~48 hours.",
            "FireHOL"),
        Define(
            "firehol-l3",
            "FireHOL Level 3",
            "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level3.netset",
            "firehol/blocklist-ipsets",
            PublicBlocklistFormat.Mixed,
            recommended: true,
            defaultEnabled: true,
            Daily,
            "Attack and spyware sources from the last ~30 days.",
            "FireHOL"),
        Define(
            "threatfox",
            "ThreatFox IOC IPs",
            "https://raw.githubusercontent.com/elliotwutingfeng/ThreatFox-IOC-IPs/main/ips.txt",
            "elliotwutingfeng/ThreatFox-IOC-IPs",
            PublicBlocklistFormat.IpAddress,
            recommended: true,
            defaultEnabled: true,
            Hourly,
            "Active malware and C2 IP indicators from Abuse.ch ThreatFox.",
            "Threat Intelligence"),
        Define(
            "crowdsec-http",
            "CrowdSec HTTP Brute-Force (community)",
            "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-generic-bf.json.txt",
            "Y3ll0w/CrowdSec-CAPI-Decisions",
            PublicBlocklistFormat.IpAddress,
            recommended: false,
            defaultEnabled: false,
            EveryTwoHours,
            "Unofficial CrowdSec community mirror focused on HTTP brute-force attempts.",
            "CrowdSec Community"),
        Define(
            "crowdsec-scan",
            "CrowdSec Port Scan (community)",
            "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/iptables-scan-multi_ports.json.txt",
            "Y3ll0w/CrowdSec-CAPI-Decisions",
            PublicBlocklistFormat.IpAddress,
            recommended: false,
            defaultEnabled: false,
            EveryTwoHours,
            "Unofficial CrowdSec community mirror focused on multi-port scanning.",
            "CrowdSec Community"),
        Define(
            "crowdsec-ssh",
            "CrowdSec SSH Brute-Force (community)",
            "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/ssh-bf.json.txt",
            "Y3ll0w/CrowdSec-CAPI-Decisions",
            PublicBlocklistFormat.IpAddress,
            recommended: false,
            defaultEnabled: false,
            EveryTwoHours,
            "Unofficial CrowdSec community mirror focused on SSH brute-force attempts.",
            "CrowdSec Community")
    ];

    public static PublicBlocklistDefinition GetById(string id) =>
        All.FirstOrDefault(d => string.Equals(d.Id, id, StringComparison.OrdinalIgnoreCase));

    private static PublicBlocklistDefinition Define(
        string id,
        string name,
        string sourceUrl,
        string sourceLabel,
        PublicBlocklistFormat format,
        bool recommended,
        bool defaultEnabled,
        TimeSpan updateInterval,
        string description,
        string category) =>
        new(id, name, sourceUrl, sourceLabel, format, recommended, defaultEnabled, updateInterval, description, category);
}
